Repository devopsfantasticfour/shopcarts, pull requests merged in 2019-03, with the labels that each got.

#11 Update Issue Template
  ISSUE_TEMPLATE.md
Labels: Technical Debt

#12 Move ISSUE Template file to .github dir
  .github/ISSUE_TEMPLATE.md
Labels: bug

#14 Copy devenv files into this repo
  .gitignore
  Vagrantfile
  requirements.txt
Labels: Technical Debt

#37 Added functions to update shopping carts
  app.py
Labels: enhancement

#42 Separate out models, services code
  app/.app.py
  app/__init__.py
  app/models.py
  app/service.py
  requirements.txt
  run.py
  setup.cfg
Labels: ShoppingCart RESTful service

#44 Add test cases for models.py and service.py
  app/models.py
  app/service.py
  tests/__init__.py
  tests/cart_factory.py
  tests/test_model.py
  tests/test_service.py
Labels: ShoppingCart RESTful service

#46 Update README file
  README.md
Labels: ShoppingCart RESTful service
